"""
Chart Analyzer
Strategy: Leverage the 9B multimodal LLM's visual understanding capability
1. Detect chart regions from page images (general image processing based on text masks, no hard-coded rules)
2. Feed detected chart regions to the multimodal LLM for understanding
3. Save LLM understanding results (structured descriptions) to the database for retrieval

Storage format:
- Chart description text appended to raw_text, automatically indexed by FTS and vector
- Chart metadata stored in content_json["charts"]
- Cropped chart images saved to the tenant directory (provided by caller)
"""
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

from ...config import CHART_VLM_MAX_WORKERS
from ...models.client import get_model_client
from .layout_analyzer import LayoutResult

logger = logging.getLogger(__name__)

try:
    import cv2
    HAS_OPENCV = True
except ImportError:
    HAS_OPENCV = False
    logger.warning("OpenCV not installed, chart region detection will be caption-based only")


class ChartDescription:
    """Chart description result"""
    def __init__(self):
        self.chart_id: str = ""
        self.chart_type: str = ""      # flowchart / architecture / data_chart / table_image / diagram / other
        self.description: str = ""     # Detailed description generated by LLM
        self.bbox: list[int] = [0, 0, 0, 0]
        self.image_path: str = ""      # Path to cropped chart image
        self.caption: str = ""         # Associated chart caption
        self.raw_text_transcript: str = ""  # Text transcript from the image
        self.core_insight: str = ""    # Core insight

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.chart_id,
            "type": self.chart_type,
            "description": self.description,
            "bbox": self.bbox,
            "image_path": self.image_path,
            "caption": self.caption,
            "raw_text_transcript": self.raw_text_transcript,
            "core_insight": self.core_insight,
        }

    def to_search_text(self) -> str:
        """Convert to searchable text"""
        # FIX: Simplified output, only keep raw extracted content, no analytical prefixes
        if self.description == "Non-chart content":
            return ""
        return self.description


class ChartAnalyzer:
    """
    Chart Analyzer
    Leverages the 9B multimodal LLM's visual understanding capability
    """

    def __init__(self, config: dict = None, images_dir: Path | None = None):
        self.config = config or {}
        self.model_client = get_model_client()
        # OpenLAD: images_dir is provided by caller (tenant directory), no longer read from settings
        self.images_dir = images_dir

        # Region detection parameters
        self.min_region_area = self.config.get("min_region_area", 15000)   # Minimum region area, skip if too small
        self.max_regions_per_page = self.config.get("max_regions_per_page", 4)  # Max regions to analyze per page
        self.min_region_wh = self.config.get("min_region_wh", 120)        # Minimum region width/height
        self.text_dilate_size = self.config.get("text_dilate_size", 25)   # Text dilation radius
        self.margin_ignore = self.config.get("margin_ignore", 15)         # Margin to ignore (pixels)

        # VLM parameters
        self.vlm_max_tokens = self.config.get("vlm_max_tokens", 1024)
        self.vlm_temperature = self.config.get("vlm_temperature", 0.2)
        self.max_image_size = self.config.get("max_image_size", 1024)     # Max side length of image sent to LLM

    def analyze_page(self, page_image: Image.Image, layout_result: LayoutResult,
                     page_text: str, doc_id: str, page_num: int) -> list[ChartDescription]:
        """
        Analyze all charts on a page

        Simplified architecture (removed 0.8B pre-screening):
            1. Detect candidate regions
            2. Perform 9B fine-grained analysis on detected regions

        Args:
            page_image: Page image (PIL Image)
            layout_result: Layout analysis result
            page_text: Page text (used for context)
            doc_id: Document ID
            page_num: Page number

        Returns:
            List of ChartDescription
        """
        if not page_image:
            logger.debug(f"Page {page_num} has no image, skip chart analysis")
            return []

        # 1. Detect candidate regions
        regions = self._detect_regions(page_image, layout_result)
        if not regions:
            logger.debug(f"Page {page_num}: no chart regions detected")
            return []

        logger.info(f"Page {page_num}: detected {len(regions)} chart region(s)")

        # P0-OPT1: Secondary filter - remove full-page regions from no_text_mask for non-image pages
        # Prevent plain text / blank pages from being incorrectly sent to the 9B VLM
        filtered_regions = []
        for r in regions[:self.max_regions_per_page]:
            if r.get("source") == "no_text_mask" and layout_result.page_type != "image_page":
                continue
            filtered_regions.append(r)
        regions = filtered_regions
        if not regions:
            logger.info(f"Page {page_num}: all regions filtered out by secondary filter")
            return []

        # Concurrent chart analysis — concurrency controlled by OPENLAD_CHART_VLM_MAX_WORKERS
        # Set this to match your LLM server's --parallel value
        charts = []
        max_workers = min(CHART_VLM_MAX_WORKERS, len(regions[:self.max_regions_per_page]))
        if max_workers < 1:
            max_workers = 1
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {}
            for idx, region in enumerate(regions[:self.max_regions_per_page]):
                future = executor.submit(
                    self._analyze_region,
                    page_image, region, page_text, doc_id, page_num, idx
                )
                futures[future] = idx

            for future in as_completed(futures):
                idx = futures[future]
                try:
                    chart = future.result(timeout=130)
                    if chart and chart.description:
                        charts.append(chart)
                        logger.info(f"Page {page_num} chart {idx}: type={chart.chart_type}, "
                                   f"desc_len={len(chart.description)}")
                except Exception as e:
                    logger.error(f"Page {page_num} chart {idx}: concurrent analysis failed: {e}")

        return charts

    def _detect_regions(self, page_image: Image.Image,
                        layout_result: LayoutResult) -> list[dict[str, Any]]:
        """
        Detect regions on the page that may contain charts

        Strategy 1: Caption-based companion search (most reliable)
        - When layout analysis finds captions like "Figure X" / "Table X"
        - Search above or below the caption for text-free regions

        Strategy 2: Inverse detection based on text mask (general supplement)
        - Use all known text blocks as a mask
        - Dilate and invert to find contiguous non-text large regions
        - Filter margins and noise

        Strategy 3: Full-page image pages
        - If the page is marked as image_page, treat the entire page as a single region
        """
        regions = []
        width, height = page_image.size

        # === Strategy 3: Full-page image pages ===
        if layout_result.page_type == "image_page":
            # Entire page is an image, analyze the whole page directly
            regions.append({
                "bbox": [0, 0, width, height],
                "type": "full_page_image",
                "caption": "",
                "source": "image_page"
            })
            return regions

        # === Strategy 1: Caption-based companion regions ===
        caption_regions = self._detect_by_caption(layout_result, width, height)
        regions.extend(caption_regions)

        # === Strategy 2: Inverse detection via text mask (always runs as supplement, no longer short-circuited by Strategy 1) ===
        if HAS_OPENCV:
            mask_regions = self._detect_by_text_mask(page_image, layout_result)
            # Remove regions that overlap with caption regions
            mask_regions = self._filter_overlapping(mask_regions, caption_regions)
            regions.extend(mask_regions)
            if mask_regions:
                logger.debug(f"Text-mask detection found {len(mask_regions)} region(s) "
                            f"(caption found {len(caption_regions)})")

        # Sort by area, prioritize analyzing larger charts
        regions.sort(key=lambda r: (r["bbox"][2] - r["bbox"][0]) * (r["bbox"][3] - r["bbox"][1]), reverse=True)

        return regions

    def _detect_by_caption(self, layout_result: LayoutResult,
                           page_width: int, page_height: int) -> list[dict[str, Any]]:
        """
        Detect chart regions based on caption positions
        When captions like "Figure X" / "TABLE X" are found, search above or below them for chart regions
        """
        regions = []
        captions = [e for e in layout_result.elements if e.element_type == "caption"]

        for cap in captions:
            cap_bbox = cap.bbox
            cap_text = str(cap.content) if cap.content else ""

            # Determine whether it's a figure or table (not hard-coded, just for classification)
            is_table = any(kw in cap_text.lower() for kw in ["表", "table"])
            region_type = "table_image" if is_table else "chart"

            # Search above the caption for chart region (charts are usually above captions)
            search_bbox = [
                0,
                max(0, cap_bbox[1] - page_height // 3),
                page_width,
                cap_bbox[1]
            ]
            region = self._find_chart_in_bbox(search_bbox, layout_result, cap_text, region_type)
            if region:
                regions.append(region)
                continue

            # Search below the caption for chart region
            search_bbox = [
                0,
                cap_bbox[3],
                page_width,
                min(page_height, cap_bbox[3] + page_height // 3)
            ]
            region = self._find_chart_in_bbox(search_bbox, layout_result, cap_text, region_type)
            if region:
                regions.append(region)

        return regions

    def _find_chart_in_bbox(self, search_bbox: list[int], layout_result: LayoutResult,
                            caption_text: str, region_type: str) -> dict[str, Any] | None:
        """
        Find a chart region within a specified bbox
        Criteria: text coverage in region < 30%, and area large enough
        """
        sx1, sy1, sx2, sy2 = search_bbox
        search_area = (sx2 - sx1) * (sy2 - sy1)
        if search_area < self.min_region_area:
            return None

        # Calculate text coverage area within the search region
        text_area = 0
        for elem in layout_result.elements:
            if elem.element_type in ("text", "title", "section-header", "list-item"):
                overlap = self._bbox_overlap_area(elem.bbox, search_bbox)
                text_area += overlap

        # If text coverage is low, consider it a chart region
        if text_area / search_area < 0.35:
            return {
                "bbox": search_bbox,
                "type": region_type,
                "caption": caption_text,
                "source": "caption_based"
            }

        return None

    def _detect_by_text_mask(self, page_image: Image.Image,
                             layout_result: LayoutResult) -> list[dict[str, Any]]:
        """
        Inverse detection based on text mask
        General image processing method, not dependent on domain knowledge
        """
        if not HAS_OPENCV:
            return []

        try:
            width, height = page_image.size
            # PIL to numpy (RGB)
            np.array(page_image.convert('RGB'))

            # Create a black mask (text areas painted white)
            mask = np.zeros((height, width), dtype=np.uint8)

            for elem in layout_result.elements:
                if elem.element_type in ("text", "title", "section-header", "caption",
                                          "footnote", "list-item", "page-header", "page-footer"):
                    x1, y1, x2, y2 = elem.bbox
                    x1, y1 = max(0, int(x1)), max(0, int(y1))
                    x2, y2 = min(width, int(x2)), min(height, int(y2))
                    if x2 > x1 and y2 > y1:
                        cv2.rectangle(mask, (x1, y1), (x2, y2), 255, -1)

            # If no text info, only return full page when explicitly marked as image_page
            # Prevent plain text scans / blank pages from being incorrectly classified as charts
            if np.sum(mask) == 0:
                if layout_result.page_type == "image_page":
                    return [{
                        "bbox": [0, 0, width, height],
                        "type": "unknown",
                        "caption": "",
                        "source": "no_text_mask"
                    }]
                return []

            # Dilate text regions to merge adjacent text blocks
            kernel = cv2.getStructuringElement(
                cv2.MORPH_RECT,
                (self.text_dilate_size, self.text_dilate_size)
            )
            dilated = cv2.dilate(mask, kernel)

            # Invert: text regions become black, non-text regions become white
            inverted = cv2.bitwise_not(dilated)

            # Ignore margins: paint margin regions black
            m = self.margin_ignore
            if m > 0:
                inverted[:m, :] = 0
                inverted[-m:, :] = 0
                inverted[:, :m] = 0
                inverted[:, -m:] = 0

            # Find contours
            contours, _ = cv2.findContours(inverted, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            regions = []
            for cnt in contours:
                x, y, w, h = cv2.boundingRect(cnt)
                area = w * h

                # Filter conditions
                if w < self.min_region_wh or h < self.min_region_wh:
                    continue
                if area < self.min_region_area:
                    continue
                # Filter areas that are too large relative to page (may be residual full page)
                if area > width * height * 0.85:
                    continue
                # Filter overly flat regions (may be separators)
                if w > h * 15 or h > w * 15:
                    continue
                # P0-OPT1: Filter narrow strips at top/bottom (headers/footers/decorative lines)
                region_top_ratio = y / height
                region_bottom_ratio = (y + h) / height
                region_height_ratio = h / height
                if (region_top_ratio < 0.08 or region_bottom_ratio > 0.92) and region_height_ratio < 0.12:
                    continue

                regions.append({
                    "bbox": [x, y, x + w, y + h],
                    "type": "detected_region",
                    "caption": "",
                    "source": "text_mask"
                })

            return regions

        except Exception as e:
            logger.warning(f"Text mask detection failed: {e}")
            return []

    def _filter_overlapping(self, new_regions: list[dict],
                            existing_regions: list[dict],
                            iou_threshold: float = 0.5) -> list[dict]:
        """Remove new regions with high overlap with existing regions"""
        filtered = []
        for nr in new_regions:
            nb = nr["bbox"]
            overlap = False
            for er in existing_regions:
                eb = er["bbox"]
                iou = self._compute_iou(nb, eb)
                if iou > iou_threshold:
                    overlap = True
                    break
            if not overlap:
                filtered.append(nr)
        return filtered

    def _compute_iou(self, bbox1: list[int], bbox2: list[int]) -> float:
        """Compute IoU between two bboxes"""
        x1 = max(bbox1[0], bbox2[0])
        y1 = max(bbox1[1], bbox2[1])
        x2 = min(bbox1[2], bbox2[2])
        y2 = min(bbox1[3], bbox2[3])

        inter = max(0, x2 - x1) * max(0, y2 - y1)
        area1 = (bbox1[2] - bbox1[0]) * (bbox1[3] - bbox1[1])
        area2 = (bbox2[2] - bbox2[0]) * (bbox2[3] - bbox2[1])
        union = area1 + area2 - inter

        return inter / union if union > 0 else 0.0

    def _bbox_overlap_area(self, bbox1: list[int], bbox2: list[int]) -> int:
        """Compute overlap area between two bboxes"""
        x1 = max(bbox1[0], bbox2[0])
        y1 = max(bbox1[1], bbox2[1])
        x2 = min(bbox1[2], bbox2[2])
        y2 = min(bbox1[3], bbox2[3])
        return max(0, x2 - x1) * max(0, y2 - y1)

    def _analyze_region(self, page_image: Image.Image, region: dict[str, Any],
                        page_text: str, doc_id: str, page_num: int,
                        region_idx: int) -> ChartDescription | None:
        """
        Use multimodal LLM to analyze a single chart region
        """
        bbox = region["bbox"]
        caption = region.get("caption", "")
        region_type = region.get("type", "")

        # V4.6 OPT-1: Skip text tables - tables identified by caption (table_image) don't need VLM analysis
        # Financial tables (balance sheets, income statements) in annual/financial reports have text already extracted by PyMuPDF
        # VLM analysis of such tables is pure waste, 12-15 seconds each time
        if region_type == "table_image":
            logger.info(f"Page {page_num} region {region_idx}: text table (table_image), "
                       f"text already extracted by PyMuPDF, skipping VLM")
            return None

        # V4.6 OPT-2: Aspect ratio filter - overly wide or tall regions are likely text blocks/table rows, not charts
        region_w = bbox[2] - bbox[0]
        region_h = bbox[3] - bbox[1]
        if region_w > 0 and region_h > 0:
            aspect_ratio = max(region_w, region_h) / min(region_w, region_h)
            if aspect_ratio > 8:  # e.g., very long horizontal or vertical strips
                logger.debug(f"Page {page_num} region {region_idx}: aspect ratio too large ({aspect_ratio:.1f}), skipping")
                return None

        # V4.5 OPT: Area filter - skip regions that are too small
        width, height = page_image.size
        page_area = width * height
        region_area = region_w * region_h
        region_ratio = region_area / page_area
        if region_ratio < 0.03:  # Skip regions smaller than 3% of page
            logger.debug(f"Page {page_num} region {region_idx}: area too small ({region_ratio:.2%}), skipping")
            return None

        try:
            # Crop chart region
            chart_image = page_image.crop(bbox)

            # Save cropped image
            chart_filename = f"{doc_id}_p{page_num}_chart{region_idx}.png"
            if self.images_dir:
                chart_path = self.images_dir / chart_filename
                chart_image.save(chart_path, "PNG")
            else:
                chart_path = None

            # P0-OPT1: 0.8B quick pre-check - filter false positives with 0.8B before sending to 9B
            # 0.8B ~100ms/image, 9B ~10-15s/image, very high ROI
            if hasattr(self.model_client, 'quick_chart_detect'):
                try:
                    is_chart = self.model_client.quick_chart_detect(str(chart_path))
                    if not is_chart:
                        logger.info(f"Page {page_num} region {region_idx}: 0.8B pre-check says not a chart, skipping 9B")
                        return None
                except Exception as e:
                    logger.debug(f"0.8B pre-check failed, falling through to 9B: {e}")

            # Build prompt
            prompt = self._build_vlm_prompt(caption, page_text)

            # Call multimodal LLM
            response = self.model_client.generate_with_image(
                prompt=prompt,
                image_path=str(chart_path),
                max_tokens=self.vlm_max_tokens,
                temperature=self.vlm_temperature,
                max_image_size=self.max_image_size
            )

            if not response or not response.strip():
                logger.warning(f"VLM returned empty for chart {region_idx} on page {page_num}")
                return None

            # Parse response
            chart = self._parse_vlm_response(response, region)
            chart.chart_id = f"{doc_id}_p{page_num}_chart{region_idx}"
            chart.image_path = str(chart_path)
            chart.bbox = bbox

            # V4.5 OPT: Quality filter - description too short means poor analysis quality, skip
            if len(chart.description) < 50:
                logger.debug(f"Page {page_num} chart {region_idx}: description too short ({len(chart.description)} chars), skipping")
                return None

            return chart

        except Exception as e:
            logger.error(f"Chart analysis failed for region {region_idx} on page {page_num}: {e}")
            return None

    def _build_vlm_prompt(self, caption: str, page_text: str) -> str:
        """
        Build prompt for the multimodal LLM
        FIX: Strictly limited to extraction mode, prohibit analysis/guess/inference
        """
        context_hint = ""
        if caption:
            context_hint = f"The caption/description of this image is: {caption}\n"
        elif page_text:
            context_hint = f"Page text summary (first 300 chars): {page_text[:300]}\n"

        prompt = f"""You are looking at a screenshot of a document page. Your task is to extract the text and data from the image without any analysis or interpretation.

{context_hint}
Rules:
1. Only output text and data that actually appear in the image
2. Do not guess, infer, or interpret the meaning of data
3. Do not add analytical statements like "this might be...", "probably...", "key insight", "conclusion"
4. If the image contains no charts (only plain text), reply with "NON_CHART_CONTENT"
5. Preserve original data precision, do not round or rewrite
6. BE CONCISE: for simple diagrams (block diagrams, flowcharts, pinouts), give a brief 2-3 sentence summary. Only exhaustively extract every label/number for data-dense tables, register maps, or specification grids.

Output format:
Type: [table/flowchart/architecture diagram/screenshot/other]

Summary:
(brief description — 2-3 sentences for simple diagrams, longer only for dense data)

Text Transcript:
(transcribe visible text — short excerpt for simple diagrams, full detail for data tables)

Data:
(list key numbers — only for data-heavy tables/charts)"""
        return prompt.strip()

    def _parse_vlm_response(self, response: str, region: dict) -> ChartDescription:
        """
        Parse VLM response
        FIX: Simplified parsing, directly store raw extracted content without secondary processing
        """
        chart = ChartDescription()
        chart.caption = region.get("caption", "")

        # Check if it's non-chart content
        if "NON_CHART_CONTENT" in response or "非图表内容" in response:
            chart.description = "Non-chart content"
            chart.core_insight = "Non-chart content"
            chart.chart_type = "non_chart"
            return chart

        # Extract type (first line)
        lines = response.strip().split('\n')
        chart.chart_type = region.get("type", "unknown")
        for line in lines[:5]:
            if line.startswith("Type:") or line.startswith("类型：") or line.startswith("类型:"):
                chart.chart_type = line.split(":", 1)[1].strip() if ":" in line else line.split("：", 1)[1].strip()
                break

        # Directly store the full response as description (raw extracted content)
        chart.description = response.strip()

        # Core insight left blank (new prompt does not generate analysis)
        chart.core_insight = ""

        # Text transcript = full response
        chart.raw_text_transcript = response.strip()

        return chart

    def _infer_chart_type(self, line: str) -> str:
        """
        Infer chart type from a line of text
        """
        line_lower = line.lower()
        type_keywords = {
            "flowchart": ["flowchart", "flow", "流程图", "流程"],
            "architecture": ["architecture", "block diagram", "架构图", "架构", "系统架构"],
            "data_chart": ["data chart", "bar chart", "line chart", "pie chart", "scatter",
                           "柱状图", "折线图", "饼图", "散点图", "数据图", "图表"],
            "table_image": ["table", "表格", "表格截图"],
            "timeline": ["timeline", "gantt", "时序图", "时间线"],
            "state_machine": ["state machine", "state diagram", "状态机", "状态图"],
            "circuit": ["circuit", "schematic", "电路图", "原理图"],
            "organization": ["org chart", "organization", "组织架构图", "组织图"],
            "pinout": ["pinout", "pin diagram", "引脚图", "封装图"],
            "product_photo": ["product", "photo", "产品图", "实物图", "照片"],
        }

        for chart_type, keywords in type_keywords.items():
            for kw in keywords:
                if kw in line_lower:
                    return chart_type

        return "unknown"

    def build_enhanced_text(self, original_text: str,
                           charts: list[ChartDescription]) -> str:
        """
        Append chart descriptions to page text so they participate in retrieval
        Returns enhanced text
        """
        if not charts:
            return original_text

        parts = [original_text]
        parts.append("\n\n=== Page Chart Content Analysis ===")

        for chart in charts:
            chart_text = chart.to_search_text()
            parts.append(chart_text)
            parts.append("---")

        return "\n\n".join(parts)
